config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/ping" => PingController.action(:ping)

  get "/login" => "sessions#new", as: 'login'
  get '/auth/google/callback' => 'sessions#create'
  get 'auth/google/error' => 'sessions#error'
  delete "/logout" => "sessions#destroy", as: 'logout'

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update] do
    resource :flag, only: [:create, :destroy], controller: 'recipe_flags'
  end

  resources :ingredients, only: [:index, :show] do
    resource :merge, only: [:create], controller: 'ingredient_merges'
  end
  resources :sources, only: [:index, :new, :create, :show, :edit, :update]

  get '/search' => 'search#index', as: 'search'

  root to: "home#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_ingredients, ->{ extending(RecipeIngredientExtension) }, inverse_of: :recipe, dependent: :destroy, autosave: true
  has_many :images, class_name: 'RecipeImage', inverse_of: :recipe, dependent: :destroy, autosave: true
  belongs_to :image, class_name: 'RecipeImage', foreign_key: :recipe_image_id, optional: true

  belongs_to :source, inverse_of: :recipes, optional: true

  has_one :flag, class_name: 'RecipeFlag', dependent: :destroy
  scope :flagged, -> { joins(:flag) }

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :title, presence: true

  include PerformsActionOnSave
  action_on_save :update_recipe_ingredients
  action_on_save :update_primary_image

  if Rails.application.config.using_postgres
    include PgSearch
    pg_search_scope :matching, against: %i(title)
  else
    scope :matching, -> (query) { where(["title LIKE ?", "%#{query}%"]) }
  end

  def ingredient_lines
    IngredientListParser.new(ingredients_text).ingredients
  end

  def update_recipe_ingredients
    names = ingredient_lines.select(&:parsed?).map(&:names).flatten.uniq
    recipe_ingredients.update_from(names)
  end

  def update_primary_image
    if (image_id = images.first.try(:id)) != recipe_image_id
      update_attribute :recipe_image_id, image_id
    end
  end

  def to_param
    "#{id}-#{title_was.parameterize}"
  end

  module RecipeIngredientExtension
    def build_from(*args)
      scoping { klass.build_from(*args) }.tap do |o|
        push(o)
      end
    end

    def update_from(ingredient_names)
      add_new(ingredient_names)
      remove_old(ingredient_names)
    end

    def named(ingredient_name)
      detect{|ri| ri.name == ingredient_name}
    end

    private

    def current_list
      map(&:name)
    end

    def add_new(list)
      new_names = list - current_list
      new_names.each { |name| build_from(name) }
    end

    def remove_old(list)
      unused_names = current_list - list
      destroy unused_names.map{ |name| matching(name) }
    end

    def matching(name)
      detect{|ri| ri.name == name}
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < AuthenticatedController
  def index
    @recipes = presentable(Recipe.includes(:image).page(params[:page]).per(48))
  end

  def show
    @recipe = presentable(Recipe.find(params[:id]))
    respond_to do |format|
      format.html
      format.yml { render plain: RecipeYmlSerializer.new(@recipe, request.host).to_yaml }
    end
  end

  def new
    @recipe = presentable(new_recipe)
  end

  def create
    recipe = Recipe.new(recipe_params)
    if recipe.save
      redirect_to recipe_path(recipe)
    else
      @recipe = presentable(recipe)
      render :new
    end
  end

  def edit
    @recipe = presentable(Recipe.find(params[:id]))
  end

  def update
    recipe = Recipe.find(params[:id])
    if recipe.update(recipe_params)
      redirect_to recipe_path(recipe)
    else
      @recipe = presentable(recipe)
      render :edit
    end
  end

  private

  def new_recipe
    if source = params[:source]
      Importer.import_from_url(source)
    else
      Recipe.new
    end
  end

  def recipe_params
    params
      .require(:recipe)
      .permit(
        :title,
        :ingredients_text,
        :instructions_text,
        :notes,
        :basic_source,
        :source_id,
        images_attributes: [:id, :source_image_url, :image_data_uri, :_destroy]
      )
      .merge(update_recipe_ingredients_on_save: true, update_primary_image_on_save: true)
  end

end

app/helpers/recipe_helper.rb
module RecipeHelper

  def button_to_toggle_recipe_flag(recipe)
    if @recipe.flag
      active_class = 'active'
      http_method = :delete
    else
      active_class = nil
      http_method = :post
    end

    content_tag(:div, id: 'RecipeFlag', class: "recipe-flag #{active_class}", refresh: 'recipe-flag') do
      form_tag(
        recipe_flag_path(@recipe),
        method: http_method,
        'tg-remote' => 1,
        'refresh-on-success' => 'recipe-flag'
      ) do
        button_tag(){ fa_icon('star') }
      end
    end
  end
end

app/views/recipes/_form.html.erb
<%= ui_form(object: @recipe, layout: ComponentHelper::FORM_ALIGNED) do |f| %>
  <%= ui_text_field(name: "title", label: "Title") %>
  <%= ui_text_field(name: "basic_source", label: "Source", placeholder: "(optional)") %>
  <%= ui_select(
    name: "source_id",
    label: "Source",
    options: Source.all.map_ary(:name, :id),
    include_blank: "Choose source&hellip;".html_safe
  ) %>

  <%= ui_field_with_label("Images", :images) do %>
    <div id="ImageUploader" class="image-upload-widget" define="{images: new Recipes.ImageChooser(this)}">
      <div id="VisibleContent" class="visible-content">
        <%= f.fields_for :images do |image_form| %>
          <% if image_form.object.new_record? %>
            <div class="image bg-cover" data-image style="background-image:url(<%= image_form.object.source_image_url %>)">
              <%= image_form.hidden_field :source_image_url %>
              <span class="remove centered" title="Remove"><%= fa_icon('trash') %></span>
            </div>
          <% else %>
            <div class="image bg-cover" data-image style="background-image:url(<%= image_form.object.image(:thumb) %>)">
              <%= image_form.hidden_field :_destroy, data: { 'remove-image' => true } %>
              <span class="remove centered" title="Remove"><%= fa_icon('trash') %></span>
            </div>
          <% end %>
        <% end %>
        <div id="FileUpload" class="image-upload" title="Select images to upload">
          <div class="centered">
            <%= fa_icon('upload') %>
          </div>
        </div>
      </div>

      <input id="FileChooser" type="file" multiple accept="image/*" style="display:none">
      <div id="ImageTemplate" class="image bg-cover" data-image style="display:none;">
        <input disabled type="hidden" data-image-data-uri name="recipe[images_attributes][NUM][image_data_uri]">
        <span class="remove centered" title="Remove"><%= fa_icon('trash') %></span>
      </div>
    </div>
  <% end %>

  <%= ui_text_area(name: "ingredients_text", label: "Ingredients") %>
  <%= ui_text_area(name: "instructions_text", label: "Instructions") %>
  <%= ui_text_area(name: "notes", label: "Notes") %>
  <%= ui_submit("Submit") %>
<% end %>

app/views/recipes/_listed_recipe.html.erb
<%= link_to recipe_path(recipe), class: 'bg-cover recipe-preview', style: "background-image: url('#{recipe.image('small')}')" do %>
  <div class="centered">
    <span class="recipe-title"><%= recipe.title %></span>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="entry style-columns">
  <div class="entry-photo">
    <img src="assets/placeholder/food/350x240/12.jpg" alt="" />
  </div>
  <div class="entry-title">
    <a href="#">African Chicken Peanut Stew</a>
  </div>
  <div class="entry-meta">
    <span class="date">21 Aug 2014</span>
  </div>
  <div class="entry-content">
    <p>Lorem ipsum dolor sit amet, con sectetur adipisicing elit, sed do eiusmod
    tempor incididunt...</p>
  </div>
  <div class="entry-controls">
    <a href="#" class="control entry-to-favorites" title="Add to favorites"> <i class="fa fa-heart-o"></i> </a><span class="control-tip">24</span>
    <a href="#" class="control entry-like" title="I like this!"> <i class="fa fa-thumbs-o-up"></i> </a> <span class="control-tip">115</span>
  </div>
</div> <!-- .entry -->

app/views/recipes/_recipe_ingredient.html.erb
<% if ingredient.parsed? %>
  <li>
    <%= ui_content_container(grid_size_big: 4, grid_size_small: 2) do %>
      <%= ui_content_section do %>
        <%= ingredient.linked_ingredient_list %>
      <% end %>
      <%= ui_content_section(grid_size_big: 3) do %>
        <div><%= ingredient.description %></div>
        <% if ingredient.note.present? %>
          <div class="ingredient-note"><%= ingredient.note %></div>
        <% end %>
      <% end %>
    <% end %>
  </li>
<% else %>
  <li>
    <div><%= ingredient.line %></div>
  </li>
<% end %>

app/views/recipes/_recipe_list.html.erb
<%= ui_content_container(grid_size_big: 4) do %>
  <% recipes.each do |recipe| %>
    <%= ui_content_section do %>
      <%= render 'recipes/listed_recipe', recipe: recipe %>
    <% end %>
  <% end %>

  <%= ui_content_section(grid_size_big: 4) do %>
    <%= paginate recipes %>
  <% end %>
<% end %>

app/views/recipes/edit.html.erb
<% set_page_title "Edit: #{@recipe.title}" %>

<%= ui_content_container do %>
  <%= ui_content_section do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/recipes/index.html.erb
<% set_page_title "Recipes" %>

<%= ui_content_container do %>
  <%= ui_content_section do %>
    <%= render 'recipes/recipe_list', recipes: @recipes %>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<% set_page_title "New Recipe" %>

<%= ui_content_container do %>
  <%= ui_content_section do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/recipes/show.html.erb
<% set_page_title @recipe.title, heading: false %>

<% content_for :side_menu do %>
  <%= ui_side_menu_link('Edit this recipe', edit_recipe_path(@recipe), separated: true) %>
<% end %>

<%= ui_content_container do %>
  <%= ui_content_section do %>
    <div class="bg-cover recipe-main-image" style="background-image:url(<%= @recipe.image('full') %>)">
      <%= button_to_toggle_recipe_flag(@recipe) %>
      <div class="centered">
        <h1 class="recipe-title"><%= @recipe.title %></h1>
      </div>
    </div>
  <% end %>

  <%= ui_editable_content_section(title: "Ingredients", object: @recipe, field: :ingredients_text) do %>
    <% @recipe.ingredient_groups.each do |group| %>
      <% if group.header %>
        <h3><%= group.header %></h3>
      <% end %>
      <ul class="ingredients-list">
        <% group.lines.each do |line| %>
          <%= render 'recipe_ingredient', ingredient: line %>
        <% end %>
      </ul>
    <% end %>
  <% end %>

  <%=
    ui_editable_content_section(title: "Instructions", object: @recipe, field: :instructions_text) do
      render_markdown @recipe.instructions_text
    end
  %>

  <% if @recipe.notes.present? %>
    <%=
      ui_editable_content_section(title: "Notes", object: @recipe, field: :notes) do
        render_markdown @recipe.notes
      end
    %>
  <% end %>

  <% if @recipe.has_source? %>
    <%= ui_content_section(title: "Source") do %>
      <div class="recipe-source">
        <% if @recipe.source %>
          <%= image_tag @recipe.source.image(:mini) %>
          <div>
            <%= link_to @recipe.source.name, source_path(@recipe.source) %>
            <% if @recipe.source.author %>
              <span class="author">by <%= @recipe.source.author %></span>
            <% end %>
          </div>
        <% end %>

        <% if @recipe.basic_source_url %>
          <span><%= link_to @recipe.basic_source_url, @recipe.basic_source_url %><span>
        <% elsif @recipe.basic_source %>
          <span><%= @recipe.basic_source %><span>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% end %>