config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/ping" => PingController.action(:ping)

  get "/login" => "sessions#new", as: 'login'
  get '/auth/google/callback' => 'sessions#create'
  get 'auth/google/error' => 'sessions#error'
  delete "/logout" => "sessions#destroy", as: 'logout'

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update] do
    resource :flag, only: [:create, :destroy], controller: 'recipe_flags'
  end

  resources :ingredients, only: [:index, :show] do
    resource :merge, only: [:create], controller: 'ingredient_merges'
  end
  resources :sources, only: [:index, :new, :create, :show, :edit, :update]

  get '/search' => 'search#index', as: 'search'

  root to: "home#index"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, inverse_of: :ingredient, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
  has_many :ingredient_names, inverse_of: :ingredient, dependent: :destroy, autosave: true

  validates :name, presence: true, uniqueness: true

  scope :not_including, -> (ing) { where.not(id: ing.id) }

  include PerformsActionOnSave
  action_on_save :ensure_ingredient_name

  def ensure_ingredient_name
    ingredient_names.by(name) || ingredient_names.create!(name: name)
  end

  def names
    ingredient_names.map(&:name)
  end

  def alternate_names
    names - [name]
  end

  def self.from(name)
    IngredientName.find_ingredient(name) || new(name: name, ensure_ingredient_name_on_save: true)
  end

  def to_param
    "#{id}-#{name_was.parameterize}"
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < AuthenticatedController

  def index
    @ingredients = presentable(Ingredient.all)
  end

  def show
    @ingredient = presentable(Ingredient.find(params[:id]))
  end

end

app/views/ingredients/index.html.erb
<% set_page_title "Ingredients" %>

<%= ui_content_container do %>
  <%= ui_content_section do %>
    <div define="{query: ''}">
      <div>
        <span>Filter ingredients:</span>
        <input type="text" placeholder="" bind="query"/>
      </div>

      <% @ingredients.sort.group_by(&:first_letter).each do |letter, ingredients| %>
        <h4 bind-show="query.length == 0"><%= letter %></h4>
        <ul class="all-ingredients">
          <% ingredients.each do |ing| %>
            <li bind-show="utils.contains('<%= escape_javascript(ing.name) %>',query)">
              <%= link_to h(ing.name).gsub(' ', '&nbsp;').html_safe, ingredient_path(ing) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/ingredients/show.html.erb
<% set_page_title @ingredient.name.titleize %>

<%= ui_content_container do %>
  <%= ui_content_section(title: "Other names") do %>
    <%= @ingredient.alternate_names.join(', ') %>
  <% end %>

  <%= ui_content_section(title: "Mergo into:") do %>
    <ul>
      <% Ingredient.not_including(@ingredient).find_each do |ing| %>
        <li><%= link_to ing.name, ingredient_merge_path(ing, id: @ingredient.id), method: :post %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>