config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/ping" => PingController.action(:ping)

  get "/login" => "sessions#new", as: 'login'
  get '/auth/google/callback' => 'sessions#create'
  get 'auth/google/error' => 'sessions#error'
  delete "/logout" => "sessions#destroy", as: 'logout'

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update] do
    resource :flag, only: [:create, :destroy], controller: 'recipe_flags'
  end

  resources :ingredients, only: [:index, :show] do
    resource :merge, only: [:create], controller: 'ingredient_merges'
  end
  resources :sources, only: [:index, :new, :create, :show, :edit, :update]

  get '/search' => 'search#index', as: 'search'

  root to: "home#index"
end

app/views/layouts/_side_menu.html.erb
<!-- Menu toggle -->
<a href="#menu" id="menuLink" class="menu-link">
  <!-- Hamburger icon -->
  <span></span>
</a>

<div id="menu">
  <div class="pure-menu">
    <%= link_to application_name, root_path, class: 'pure-menu-heading' %>

    <ul class="pure-menu-list">
      <% if logged_in? %>
        <%= ui_side_menu_link("Recipes", recipes_path, active: recipes_section?) %>
        <%= ui_side_menu_link("Ingredients", ingredients_path, active: ingredients_section?) %>
        <%= ui_side_menu_link("Sources", sources_path, active: sources_section?) %>

        <%= yield(:side_menu) if content_for?(:side_menu) %>

        <%= ui_side_menu_link("New recipe", new_recipe_path, active: new_recipe_section?, separated: true) %>
        <%= ui_side_menu_link("New source", new_source_path, active: new_source_section?) %>
        <%= ui_side_menu_link("Bookmarklet", '#', disabled: true) %>

        <%= ui_side_menu_link("Sign out", logout_path, separated: true, link_params: { method: :delete }) %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" href="<%= asset_path 'favicon.png' %>">

  <title><%= head_title %></title>

  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css">
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= content_for?(:application_content) ? yield(:application_content) : yield %>
</body>
</html>

app/views/layouts/main.html.erb
<% content_for :application_content do %>
  <div id="layout" define="{utils: new Recipes.Utils}">
    <div id="main">
      <% if page_heading %>
        <div class="header">
          <h1><%= page_heading %></h1>
        </div>
      <% end %>

      <div class="content">
        <%= content_for?(:main_content) ? yield(:main_content) : yield %>
      </div>
    </div>

    <%= render 'layouts/side_menu' %>
  </div>
<% end %>

<%= render template: "layouts/application" %>